### ISSUE TITLE
Add CHECK/REQUIRE_AT() variants

### ISSUE THREAD

**Issue by vadz** [philsquared/Catch#516]
I think this is the same as #91, but I believe the request wasn't explained very well there so I'd like to try to do it again.

The idea is to allow using CATCH macros with an extra `SourceLineInfo` argument to make it appear as if they failed at some other place instead of the line they are actually at.

Why would this be needed? Consider this pseudo-code:

```
void CheckAlmostEqual(Foo const& first, Foo const& second)
{
   CHECK( some_complicated_function_checking_for_equality(first, second) );
}

TEST_CASE("Check almost equality")
{
   CheckAlmostEqual(Foo(1), Foo(2));
}
```

If the check fails, you want to be pointed to the line inside the test, even if you're actually using a helper function to simplify it. Currently it seems to be impossible to do this.

The proposed solution would work like this:

```
void CheckAlmostEqual(Foo const& first, Foo const& second, Catch::SourceLineInfo& source)
{
   CHECK_AT( some_complicated_function_checking_for_equality(first, second), source );
}

TEST_CASE("Check almost equality")
{
   CheckAlmostEqual(Foo(1), Foo(2), SOURCE_LINE_INFO);
}
```

Would patches/PRs implementing this be welcome?

**Comment by Darelbi** [comment]
I'm not sure Catch allows Macros outside of test cases, there's much information behind the scenes. one way to implement that would be throwing an exception that is caught inside TEST_CASE. Actually I created my assertion function that throws an exception from helper functions, all I do is checking that the helper function throws or not throws when called inside a TEST_CASE.

I'd like also Catch to support catching only certain exception types.

    REQUIRE_THROWS ( exp, exceptionType)

That can expand to

    bool expectedException = false;
    try{
        exp;
    }catch( exceptionType & e){
        expectedException  =true;
    }catch(...){
    }

**Comment by vadz** [comment]
@Darelbi was your reply really meant to be done in this issue? I don't see how is this relevant to be honest...

**Comment by martinmoene** [comment]
>I'd like also Catch to support catching only certain exception types.

It's called [REQUIRE_THROWS_AS( expression, exception type )](https://github.com/philsquared/Catch/blob/master/docs/assertions.md#exceptions)

**Comment by Darelbi** [comment]
Sorry. I didn't wanted to open a new ticket since I opened already one. I see hard implementing such feature without using exceptions, wich could be the chance to add some more features related to exceptions.

I think SOURCE_LINE_INFO argument (unless needed to select a "different" overload) is not necessary at all.

    // all information needed is embedded in the new exception
    #define CHECK_AT (x) if(!!(x)) throw Catch::HelperFailAtLineException( __LINE__);

the problem is that alters the flow right? (wich can be the chance to review exceptions in Catch)

**Comment by vadz** [comment]
No, sorry, it seems like explaining it is even harder than I thought :-(

`SOURCE_LINE_INFO` is absolutely vital, this proposal makes no sense without it. Just look at the simple example at the end. The idea is that any failures will be reported at the line where `CheckAlmostEqual()` is called, as this is where you want to look, not at the line with `CHECK_AT()` itself.

I'm also still puzzled by why do you think this is related to the exceptions at all, AFAICS this has nothing to do with them. And I'm quite sure it's better to open new tickets for separate issues.

**Comment by philsquared** [comment]
I think @Darelbi's suggestion is to use an exception from the helper function to communicate the failure, but catch it in the test case itself and record it as a failure there (so you have the file/ line# in the test case).
That can be made to work but I think it's fighting the system a bit, and more work than I'd like to do in my test code (btw, @Darelbi, there's certainly no limitation on assertions in functions outside a test case - as long as the test case is somewhere on the stack at the time!)

So, going back to the original problem - how to get file/ line# of the location in the test case that *called* the helper function? The way I do this sort of thing is just to start a section immediately before calling the helper. Something like this:

`SECTION( "Calling helper function - put better description here" )
  CheckAlmostEqual(Foo(1), Foo(2));`

Now the file/ line# of the section is recorded (as well as the assertion) - and you're working *with* Catch rather than against it - and no new features are required :-)

However, with your specific example it looks like you may be trying to do tolerance matches with floating point values? In which case `Approx` would be the better tool.
If not you might also consider writing a `Matcher` (not documented yet - but you can probably work it out - let me know if you want more info on that).

**Comment by vadz** [comment]
@philsquared Sorry, now it's my turn to be missing something: how/where is the section location recorded and, most importantly, output? I don't see it anywhere in this simple test:

	% cat -n tst.cpp
	     1  #define CATCH_CONFIG_MAIN
	     2  #include <catch.hpp>
	     3  #include <cmath>
	     4
	     5  void CheckClose(int x, int y)
	     6  {
	     7      CHECK( std::abs(x - y) <= 1 );
	     8  }
	     9
	    10  TEST_CASE("Check close")
	    11  {
	    12      CheckClose(1, 1);
	    13      CheckClose(1, 2);
	    14      CheckClose(2, 1);
	    15
	    16      SECTION("this is going to fail"); {
	    17          CheckClose(0, 2);
	    18      }
	    19  }
	% g++ -Wall -I. tst.cpp && ./a.out
	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	a.out is a Catch v1.2.1 host application.
	Run with -? for options

	-------------------------------------------------------------------------------
	Check close
	-------------------------------------------------------------------------------
	tst.cpp:10
	...............................................................................

	tst.cpp:7: FAILED:
	  CHECK( std::abs(x - y) <= 1 )
	with expansion:
	  2 <= 1

	===============================================================================
	test cases: 1 | 1 failed
	assertions: 4 | 3 passed | 1 failed

As you can see, only line 7 appears in the output, while I want the line 17.

Also, I did use "approximate" match in this example, but the real code does something completely different, so this is not really related to `Approx` (which is, of course, useful in its own right). Writing a custom matcher would work, of course, but it's a heavier solution and I'd have a few of those to write as I'm transitioning a big existing unit test suite to CATCH...

**Comment by philsquared** [comment]
Sorry I missed this at the time.
If you're still watching (@vadz, especially), this turned out to be a bug in the console reporter where it was using the line # of the test case rather than the section. I have now fixed this on master (ab44fb6811f1fee96fcb66ceb448602686bc5e41) and it will be in the next patch release.

With that fix I believe my suggestion addresses the original issue - but let me know if you think otherwise. I'll close this shortly if I don't hear anything.

**Comment by vadz** [comment]
@philsquared Sorry, but applying ab44fb6811f1fee96fcb66ceb448602686bc5e41 to `catch.hpp` v1.7.1 doesn't seem to change anything, the output is still exactly the same as [before](https://github.com/philsquared/Catch/issues/516#issuecomment-149367596). Does it work with this `tst.cpp` example for you?

FWIW I'm not sure I really want to create separate `SECTION`s just for this in any case, IMHO this is semantically wrong (sections are for different sub-parts of the test and I don't have anything like this here). But it's true that this could be used as a workaround -- if it worked.

Out of curiosity, what exactly is the objection to adding `CATCH_{CHECK,REQUIRE}_AT` macro variants? This seems like such a natural generalization to me (instead of hard-coding the position, make it a parameter), yet people seems to very unenthusiastic about it. What am I missing?

**Comment by philsquared** [comment]
Sorry I should have been clearer. It's on master - in the separate (source) includes - but we haven't generated a new single_include yet - hence me saying, " will be in the next patch release". That will be 1.7.2 and will likely happen tomorrow.

As for why use `SECTION`s - and why not `_AT` variants - the latter extends the framework with more code and more interface (and more complexity) for a narrow use case that can be easily achieved using the `SECTION`s approach. That's only a good reason if I can convince you that using `SECTION`s like this is a good approach :-)

In fact I'm not sure that `SECTION`s are the best approach here after all. They were for a few cases I've had that looked similar at first - but in your case you're using a helper function but want to make it work almost like a custom assertion. Does that sound about right?

In that case I think a Matcher would be the best approach. I'm just about to update the current, undocumented, Matchers impl with something simpler and nicer to work with and will document it and make it officially part of the public API. I have the new implementation on a branch now (https://github.com/philsquared/Catch/tree/new-matchers) if you want to take a look at it.

But what do you think about that approach for your purposes?

Your example would end up looking something like:

```c++
TEST_CASE("Check almost equality")
{
   CHECK_THAT( Foo(1), AlmostEquals( Foo(2) );
}
```

**Comment by vadz** [comment]
> you're using a helper function but want to make it work almost like a custom assertion. Does that sound about right?

I admit I don't actually the details of the test I was writing 1.5 years ago, but I think this is indeed an accurate description.

The important thing is that it's natural to write this helper function using normal `CHECK`s, i.e. it verifies several properties of the object (or compares several fields of two objects). I'm not sure if it's going to be as convenient to do it with matchers.

Actually, thinking more about this, the closest thing that could be done to what I want without changing CATCH would be to use `INFO` before each call to this helper function, probably. It could even be just `INFO(__LINE__)`, e.g. this:

	% cat -n tst.cpp
	     1  #define CATCH_CONFIG_MAIN
	     2  #include <catch.hpp>
	     3  #include <cmath>
	     4
	     5  void CheckClose(int x, int y)
	     6  {
	     7      CHECK( std::abs(x - y) <= 1 );
	     8  }
	     9
	    10  TEST_CASE("Check close")
	    11  {
	    12      CheckClose(1, 1);
	    13      CheckClose(1, 2);
	    14      CheckClose(2, 1);
	    15
	    16      INFO("at line " << __LINE__); CheckClose(0, 2);
	    17  }

results almost in the same output as I wanted:
```
tst.cpp:7: FAILED:
  CHECK( std::abs(x - y) <= 1 )
with expansion:
  2 <= 1
with message:
  at line 16
```

And I probably could define a macro to hide both `INFO` and `CheckClose()` inside it... It's still not nice as having built-in support for this, but probably good enough.

**Comment by philsquared** [comment]
The trouble with the helper function, other than the file/ line info, is that you also lose the descriptive breakdown of inputs and component parts.
A matcher is a little more involved to write, yes - but only because it allows you to do all those things - and all in a consistent and standardised way that works with the framework rather than trying to hook in at too low an level.

[v1.7.2](https://github.com/philsquared/Catch/releases/tag/v1.7.2) is released now - so that fixes the `SECTION` file/ line bug mentioned previously.

It also means I've now pushed my matchers changes, including docs, to master (note: not in the  single include yet). See the docs here: https://github.com/philsquared/Catch/blob/master/docs/matchers.md

**Comment by vadz** [comment]
OK, thanks for the explanations and let's close this -- in the worst case, I'll reopen it later if I find some concrete example of something that can't be (comfortably) done using matchers.

But, just to be complete, I'm still missing the point of the section file/line bug fix as I see exactly the same output [as before](https://github.com/philsquared/Catch/issues/516#issuecomment-149367596) even with v1.7.2.

**Comment by horenmar** [comment]
@vadz  If you remove the semicolon after defining section, you should get something like this
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
a.out is a Catch v1.7.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
Check close
  this is going to fail
-------------------------------------------------------------------------------
pragma_test.cpp:16
...............................................................................

pragma_test.cpp:7: FAILED:
  CHECK( std::abs(x - y) <= 1 )
with expansion:
  2 <= 1

===============================================================================
test cases: 1 | 1 failed
assertions: 4 | 3 passed | 1 failed
```
Now it shows that the last section visited before failure at line 7 was at line 16.

**Comment by vadz** [comment]
Oops. You're totally correct, of course, I completely failed to see this bogus semicolon (both 1.5 years ago and today...), sorry.

**Comment by philsquared** [comment]
Ha! I didn't spot that either - and I was just about to start looking into that!

**Comment by horenmar** [comment]
That's the magic of enabled warnings. 😄
